---
abstract: 'Parse SQL table output'
author:
  - 'Ingy döt Net <ingy@ingy.net>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Parse::SQLOutput
name: Parse-SQLOutput
no_index:
  directory:
    - inc
    - t
requires:
  Mo: 0
  perl: 5.8.3
resources:
  homepage: https://github.com/ingydotnet/parse-sqloutput-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/parse-sqloutput-pm.git
    web: https://github.com/ingydotnet/parse-sqloutput-pm/tree
version: 0.01
